###  Users
#GET http://localhost:3000/users
#Content-Type: application/json
#
#{
#  "login": "ayman",
###  "email": "a@a.com",
#  "password": "password123",
#  "elo": 500,
#  "media": "default.png",
#  "isBanned": false,
#  "isValid": false
#}

### Roles
#PATCH http://localhost:3000/users/2
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibG9naW4iOiJheW1hbiIsImlkX3JvbGUiOjIsImlhdCI6MTY4ODUwMDkzOSwiZXhwIjoxNjg4NTA0NTM5fQ.LFg4d1GI3MysOG8uULO9k0oyPPY6CuJHKxIiffnueUs
#Content-Type: application/json
#
#{
#    "id_role": 1
#}

###
GET http://localhost:3000/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJiZWRkYSIsImlkX3JvbGUiOjEsImlhdCI6MTY4ODUwMTE4OCwiZXhwIjoxNjg4NTA0Nzg4fQ.5inlv-c5NdWn06nnsix_p8ZFzdKD8C-LlKqSHcJrnR0

############
### Auth ###
############CNF
#POST http://localhost:3000/register
#Content-Type: application/json
#
#{
#  "login": "bedda",
###  "email": "b@a.com",
#  "password": "password123",
#  "elo": 500,
#  "media": "default.png",
#  "isBanned": false,
#  "isValid": false
#}
###
#POST http://localhost:3000/login
#Content-Type: application/json
#
#{
###  "email": "b@a.com",
#  "password": "password123"
#}