##  Users
DELETE http://localhost:3000/users
Content-Type: application/json

{
  "id": "sIjoiYXltb3g3NTBAZ21haWwuY29tIiwiaWF0IjoxNjkwNDUyMDkxLCJleHAiOjE2OTA0NTkyOTF9.qoZ_VSZqyufxcJx-PFk9CEFObMonjklovvI-pmmSLqc"
}

### Articles
#POST http://localhost:3000/articles
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhZG1pbiIsImlkX3JvbGUiOjEsImlzVmFsaWQiOnRydWUsImlzQmFubmVkIjpmYWxzZSwiaWF0IjoxNjg5MjQ4ODM2LCJleHAiOjE2ODkyNTk2MzZ9.UMnUqqf6i0Mw8sjJ31TiwhiHhlXWlYEQkwW3NFIPY5o
#Content-Type: application/json
#
#{
#    "libelle": "skin test",
#    "price": 800,
#    "media": "default.png",
#    "id_money": 1
#}

### Daily rewards
#POST http://localhost:3000/owns
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhZG1pbiIsImlkX3JvbGUiOjEsImlzVmFsaWQiOnRydWUsImlzQmFubmVkIjpmYWxzZSwibGFzdERhaWx5UmV3YXJkRGF0ZSI6bnVsbCwiaWF0IjoxNjg5ODY0OTk3LCJleHAiOjE2ODk4NzU3OTd9.0Q-04BUXA0PTZUwGL8TR1qW-74uEtkZet197nQUDxGQ
#Content-Type: application/json

### Buy Article money premium
#PATCH http://localhost:3000/owns/11/buy-money
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhZG1pbiIsImlkX3JvbGUiOjEsImlzVmFsaWQiOnRydWUsImlzQmFubmVkIjpmYWxzZSwibGFzdERhaWx5UmV3YXJkRGF0ZSI6IjIwMjMtMDctMjBUMTY6MzU6MDcuMzA4WiIsImlhdCI6MTY4OTk0NTM1NSwiZXhwIjoxNjg5OTU2MTU1fQ.xoPws5kE2uYTAgkqb74EYLnjRaoidRNb8vNjittxIio
#Content-Type: application/json

#GET http://localhost:3000/owns
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhZG1pbiIsImlkX3JvbGUiOjEsImlzVmFsaWQiOnRydWUsImlzQmFubmVkIjpmYWxzZSwiaWF0IjoxNjg5NTI1Mjc4LCJleHAiOjE2ODk1MzYwNzh9.HTk0nJoPrnmJzpNOqym54h8BYsktbrQTZYpZ_6Xt2LQ

### Money
#POST http://localhost:3000/moneys
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJiZWRkYSIsImlkX3JvbGUiOjEsImlzVmFsaWQiOmZhbHNlLCJpc0Jhbm5lZCI6ZmFsc2UsImlhdCI6MTY4OTA4NDQyMSwiZXhwIjoxNjg5MDk1MjIxfQ.tB54P3eccgNBoXmcIUIFgxfu60yn3f6rf9-Xdah3dr8
#Content-Type: application/json
#
#{
#    "type" : "euro"
#}


#### Buy article
#POST http://localhost:3000/articles/24/buy
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJhZG1pbiIsImlkX3JvbGUiOjEsImlzVmFsaWQiOnRydWUsImlzQmFubmVkIjpmYWxzZSwiaWF0IjoxNjg5NjA5MTEwLCJleHAiOjE2ODk2MTk5MTB9.s7W202jXlI41LC5x6dlJp77t9QDFz6R1pHxDNfUScNw
#Content-Type: application/json

#GET http://localhost:3000/buys
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJhZG1pbiIsImlkX3JvbGUiOjEsImlzVmFsaWQiOnRydWUsImlzQmFubmVkIjpmYWxzZSwibGFzdERhaWx5UmV3YXJkRGF0ZSI6bnVsbCwiaWF0IjoxNjg5OTcyMDE2LCJleHAiOjE2ODk5ODI4MTZ9.wPQ-fUgJkUpKRWiMfspHpf89SCDsbfjgxISrlZnhpmQ

###
#GET http://localhost:3000/roles
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJiZWRkYSIsImlkX3JvbGUiOjEsImlhdCI6MTY4ODUwMTE4OCwiZXhwIjoxNjg4NTA0Nzg4fQ.5inlv-c5NdWn06nnsix_p8ZFzdKD8C-LlKqSHcJrnR0

############
### Auth ###
############CNF
#POST http://localhost:3000/register
#Content-Type: application/json
#
#{
#  "login": "bedda",
###  "email": "b@a.com",
#  "password": "password123",
#  "elo": 500,
#  "media": "default.png",
#  "isBanned": false,
#  "isValid": false
#}
##

### Buy premium money
#PATCH http://localhost:3000/owns/5/buy-money
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJiZWRkYSIsImlkX3JvbGUiOjEsImlzVmFsaWQiOmZhbHNlLCJpc0Jhbm5lZCI6ZmFsc2UsImlhdCI6MTY4OTE3MzU5OCwiZXhwIjoxNjg5MTg0Mzk4fQ.8XNOaEp4Ql2UMX5QCxZWuXx-uQ5yndWkt3VOixzs3Eo
#Content-Type: application/json

###
#POST http://localhost:3000/login
#Content-Type: application/json
#
#{
###  "email": "admin@domain.com",
#  "password": "password"
#}