###  Users
#GET http://localhost:3000/users
#Content-Type: application/json
#
#{
#  "login": "ayman",
###  "email": "a@a.com",
#  "password": "password123",
#  "elo": 500,
#  "media": "default.png",
#  "isBanned": false,
#  "isValid": false
#}

### Articles
POST http://localhost:3000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibG9naW4iOiJqb2huX2RvZSIsImlkX3JvbGUiOjIsImlhdCI6MTY4ODk5ODc3MSwiZXhwIjoxNjg5MDAyMzcxfQ.R9_nbNsG0HHXaTgHT8cG-XElSyqCEhTl-RAPfNGRSNk
Content-Type: application/json

{
    "libelle": "skin aid",
    "price": 50,
    "media": "default.png",
    "id_money": 1
}

### Buy article
#POST http://localhost:3000/articles/1/buy
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJiZWRkYSIsImlkX3JvbGUiOjEsImlhdCI6MTY4ODk5NTU1NSwiZXhwIjoxNjg4OTk5MTU1fQ.7PV5bDvPVeTETR4HRgC0R_SdpzaBF64mZ2gFZyli7Kg
#Content-Type: application/json

###
#GET http://localhost:3000/roles
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibG9naW4iOiJiZWRkYSIsImlkX3JvbGUiOjEsImlhdCI6MTY4ODUwMTE4OCwiZXhwIjoxNjg4NTA0Nzg4fQ.5inlv-c5NdWn06nnsix_p8ZFzdKD8C-LlKqSHcJrnR0

############
### Auth ###
############CNF
#POST http://localhost:3000/register
#Content-Type: application/json
#
#{
#  "login": "bedda",
###  "email": "b@a.com",
#  "password": "password123",
#  "elo": 500,
#  "media": "default.png",
#  "isBanned": false,
#  "isValid": false
#}
###
#POST http://localhost:3000/login
#Content-Type: application/json
#
#{
###  "email": "john.doe@example.com",
#  "password": "password123"
#}