name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    # Install Docker Compose
    - name: Docker Compose Install
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/docker-compose

    # Build and start your Docker containers
    - name: Build the Docker Compose stack
      run: docker-compose up -d

    # Run your database migration
    - name: Run database migration
      run: docker-compose exec server node migrate force

    # Run your tests
    - name: Run tests
      run: docker-compose exec server npm test