name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    # Install Docker Compose
    - name: Docker Compose Install
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/docker-compose

    # Build and start your Docker containers
    - name: Build the Docker Compose stack
      run: docker-compose up -d

    # Install dependencies
    - name: Install Node.js dependencies
      run: docker-compose exec -T server npm install

    # Wait for the database to be ready
    - name: Wait for database
      run: |
        wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /tmp/wait-for-it.sh
        chmod +x /tmp/wait-for-it.sh
        /tmp/wait-for-it.sh db:5432 --timeout=30

    # Run your database migration
    - name: Run database migration
      run: docker-compose exec -T server node migrate force

    # Run your tests
    - name: Run tests
      run: docker-compose exec server npm test