name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    # Install Docker Compose
    - name: Docker Compose Install
      run: |
        sudo rm /usr/local/bin/docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
        chmod +x docker-compose
        sudo mv docker-compose /usr/local/bin/docker-compose

    # Build and start your Docker containers
    - name: Build the Docker Compose stack
      run: docker-compose up -d

    # Install dependencies
    - name: Install Node.js dependencies
      run: docker-compose exec -T server npm install

    # Run security checks with Snyk
    - name: Run Snyk to check for vulnerabilities
      run: docker-compose exec -T server snyk auth ${{ secrets.SNYK_TOKEN }}
      
    # Run security checks with Snyk
    - name: Run Snyk to check for vulnerabilities
      run: docker-compose exec -T server npx snyk test --all-projects --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # Run your database migration
    - name: Run database migration
      run: docker-compose exec -T server node migrate force

    # Run your database migration
    - name: Run migration
      run: docker-compose exec -T server node fixtures/index.js

    # Run your tests u
    - name: Run tests
      run: docker-compose exec -T server npm test